set1={"blue","green"}
set2={"blue","yellow"}
difference=set1.difference(set2)
difference2=set2.difference(set1)
difference.update(difference2)
print(difference)
set1={1,2,3,4,5}
set2={1,5,6,7,8,9}
difference=set1.difference(set2)
difference2=set2.difference(set1)
difference.update(difference2)
print(difference)
